// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/HumanResources/Department")]
    [ApiController]
    public class HumanResources_DepartmentController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public HumanResources_DepartmentController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_HumanResources_Department")]
        public async Task<ActionResult<IEnumerable<HumanResources.Department>>> ListDepartment(int pageIndex, int pageSize)
        {
            return await _db.HumanResources_Department.OrderBy(x => x.DepartmentID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("{departmentID}", Name = "GetById_HumanResources_Department")]
        public async Task<ActionResult<HumanResources.Department>> GetDepartment(short departmentID)
        {
            var result = await _db.HumanResources_Department.FirstOrDefaultAsync(x => x.DepartmentID == departmentID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_HumanResources_Department")]
        public async Task<IActionResult> CreateDepartment([FromBody] HumanResources.Department value)
        {
            _db.HumanResources_Department.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("{departmentID}", Name = "Edit_HumanResources_Department")]
        public async Task<IActionResult> EditDepartment(short departmentID, [FromBody] HumanResources.Department value)
        {
            var existing = await _db.HumanResources_Department.FirstOrDefaultAsync(x => x.DepartmentID == departmentID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.DepartmentID = value.DepartmentID;
			existing.Name = value.Name;
			existing.GroupName = value.GroupName;
			existing.ModifiedDate = value.ModifiedDate;

            _db.HumanResources_Department.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_HumanResources_Department")]
        public async Task<IActionResult> DeleteDepartment(short departmentID)
        {
            var existing = await _db.HumanResources_Department.FirstOrDefaultAsync(x => x.DepartmentID == departmentID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.HumanResources_Department.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}