// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/HumanResources/JobCandidate")]
    [ApiController]
    public class HumanResources_JobCandidateController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public HumanResources_JobCandidateController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_HumanResources_JobCandidate")]
        public async Task<ActionResult<IEnumerable<HumanResources.JobCandidate>>> ListJobCandidate(int pageIndex, int pageSize)
        {
            return await _db.HumanResources_JobCandidate.OrderBy(x => x.JobCandidateID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("{jobCandidateID}", Name = "GetById_HumanResources_JobCandidate")]
        public async Task<ActionResult<HumanResources.JobCandidate>> GetJobCandidate(int jobCandidateID)
        {
            var result = await _db.HumanResources_JobCandidate.FirstOrDefaultAsync(x => x.JobCandidateID == jobCandidateID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_HumanResources_JobCandidate")]
        public async Task<IActionResult> CreateJobCandidate([FromBody] HumanResources.JobCandidate value)
        {
            _db.HumanResources_JobCandidate.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("{jobCandidateID}", Name = "Edit_HumanResources_JobCandidate")]
        public async Task<IActionResult> EditJobCandidate(int jobCandidateID, [FromBody] HumanResources.JobCandidate value)
        {
            var existing = await _db.HumanResources_JobCandidate.FirstOrDefaultAsync(x => x.JobCandidateID == jobCandidateID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.JobCandidateID = value.JobCandidateID;
			existing.BusinessEntityID = value.BusinessEntityID;
			existing.Resume = value.Resume;
			existing.ModifiedDate = value.ModifiedDate;

            _db.HumanResources_JobCandidate.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_HumanResources_JobCandidate")]
        public async Task<IActionResult> DeleteJobCandidate(int jobCandidateID)
        {
            var existing = await _db.HumanResources_JobCandidate.FirstOrDefaultAsync(x => x.JobCandidateID == jobCandidateID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.HumanResources_JobCandidate.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}