SELECT 
	  c.TABLE_CATALOG AS TableCatalog
	, c.TABLE_SCHEMA AS TableSchema
	, c.TABLE_NAME AS TableName
	, c.COLUMN_NAME AS ColumnName
	, c.ORDINAL_POSITION AS OrdinalPosition
	, CASE
		WHEN c.IS_NULLABLE = 'YES' THEN 1
		ELSE 0
	  END AS IsNullable
	, c.DATA_TYPE AS [DataType]
FROM 
	INFORMATION_SCHEMA.COLUMNS AS c
	JOIN INFORMATION_SCHEMA.TABLES AS t ON c.TABLE_SCHEMA = t.TABLE_SCHEMA AND c.TABLE_NAME = t.TABLE_NAME
WHERE
	t.TABLE_TYPE = 'BASE TABLE'