SELECT
	  tc.CONSTRAINT_CATALOG AS ConstraintCatalog
	, tc.TABLE_SCHEMA AS TableSchema
	, tc.TABLE_NAME AS TableName
	, kcu.COLUMN_NAME AS ColumnName
	, tc.CONSTRAINT_NAME AS ConstraintName
	, CASE
		WHEN tc.CONSTRAINT_TYPE = 'PRIMARY KEY' THEN 0
		WHEN tc.CONSTRAINT_TYPE = 'FOREIGN KEY' THEN 1 
		WHEN tc.CONSTRAINT_TYPE = 'UNIQUE' THEN 2 
		WHEN tc.CONSTRAINT_TYPE = 'CHECK' THEN 3
		WHEN tc.CONSTRAINT_TYPE = 'DEFAULT' THEN 4
		ELSE -1
	  END AS ConstraintType
	, CONSTRAINT_TYPE
	, kcu.ORDINAL_POSITION AS OrdinalPosition
FROM 
	INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS kcu
	JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS tc ON 
		kcu.CONSTRAINT_CATALOG = tc.CONSTRAINT_CATALOG
		AND kcu.CONSTRAINT_SCHEMA = tc.CONSTRAINT_SCHEMA
		AND kcu.TABLE_NAME = tc.TABLE_NAME
		AND kcu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME