CREATE ROLE TestRunnerRole;
GO
GRANT CONNECT TO TestRunnerRole
GO
GRANT SELECT, INSERT, UPDATE, DELETE, VIEW DEFINITION ON SCHEMA::dbo TO TestRunnerRole
GO
GRANT SELECT, INSERT, UPDATE, DELETE, VIEW DEFINITION ON SCHEMA::Demo TO TestRunnerRole
GO
ALTER ROLE TestRunnerRole ADD MEMBER TestRunnerUser
GO
