// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Sales/PersonCreditCard")]
    [ApiController]
    public class Sales_PersonCreditCardController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Sales_PersonCreditCardController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Sales_PersonCreditCard")]
        public async Task<ActionResult<IEnumerable<Sales.PersonCreditCard>>> ListPersonCreditCard(int pageIndex, int pageSize)
        {
            return await _db.Sales_PersonCreditCard.OrderBy(x => x.BusinessEntityID).ThenBy(x => x.CreditCardID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("businessEntityID/{businessEntityID}/creditCardID/{creditCardID}", Name = "GetById_Sales_PersonCreditCard")]
        public async Task<ActionResult<Sales.PersonCreditCard>> GetPersonCreditCard(int businessEntityID, int creditCardID)
        {
            var result = await _db.Sales_PersonCreditCard.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID && x.CreditCardID == creditCardID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Sales_PersonCreditCard")]
        public async Task<IActionResult> CreatePersonCreditCard([FromBody] Sales.PersonCreditCard value)
        {
            _db.Sales_PersonCreditCard.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("businessEntityID/{businessEntityID}/creditCardID/{creditCardID}", Name = "Edit_Sales_PersonCreditCard")]
        public async Task<IActionResult> EditPersonCreditCard(int businessEntityID, int creditCardID, [FromBody] Sales.PersonCreditCard value)
        {
            var existing = await _db.Sales_PersonCreditCard.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID && x.CreditCardID == creditCardID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.BusinessEntityID = value.BusinessEntityID;
			existing.CreditCardID = value.CreditCardID;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Sales_PersonCreditCard.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Sales_PersonCreditCard")]
        public async Task<IActionResult> DeletePersonCreditCard(int businessEntityID, int creditCardID)
        {
            var existing = await _db.Sales_PersonCreditCard.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID && x.CreditCardID == creditCardID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Sales_PersonCreditCard.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}