// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Sales/SalesPersonQuotaHistory")]
    [ApiController]
    public class Sales_SalesPersonQuotaHistoryController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Sales_SalesPersonQuotaHistoryController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Sales_SalesPersonQuotaHistory")]
        public async Task<ActionResult<IEnumerable<Sales.SalesPersonQuotaHistory>>> ListSalesPersonQuotaHistory(int pageIndex, int pageSize)
        {
            return await _db.Sales_SalesPersonQuotaHistory.OrderBy(x => x.BusinessEntityID).ThenBy(x => x.QuotaDate).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("businessEntityID/{businessEntityID}/quotaDate/{quotaDate}", Name = "GetById_Sales_SalesPersonQuotaHistory")]
        public async Task<ActionResult<Sales.SalesPersonQuotaHistory>> GetSalesPersonQuotaHistory(int businessEntityID, DateTime quotaDate)
        {
            var result = await _db.Sales_SalesPersonQuotaHistory.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID && x.QuotaDate == quotaDate);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Sales_SalesPersonQuotaHistory")]
        public async Task<IActionResult> CreateSalesPersonQuotaHistory([FromBody] Sales.SalesPersonQuotaHistory value)
        {
            _db.Sales_SalesPersonQuotaHistory.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("businessEntityID/{businessEntityID}/quotaDate/{quotaDate}", Name = "Edit_Sales_SalesPersonQuotaHistory")]
        public async Task<IActionResult> EditSalesPersonQuotaHistory(int businessEntityID, DateTime quotaDate, [FromBody] Sales.SalesPersonQuotaHistory value)
        {
            var existing = await _db.Sales_SalesPersonQuotaHistory.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID && x.QuotaDate == quotaDate);
            if (existing == null)
            {
                return NotFound();
            }

			existing.BusinessEntityID = value.BusinessEntityID;
			existing.QuotaDate = value.QuotaDate;
			existing.SalesQuota = value.SalesQuota;
			existing.rowguid = value.rowguid;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Sales_SalesPersonQuotaHistory.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Sales_SalesPersonQuotaHistory")]
        public async Task<IActionResult> DeleteSalesPersonQuotaHistory(int businessEntityID, DateTime quotaDate)
        {
            var existing = await _db.Sales_SalesPersonQuotaHistory.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID && x.QuotaDate == quotaDate);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Sales_SalesPersonQuotaHistory.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}