// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Sales/SalesOrderHeaderSalesReason")]
    [ApiController]
    public class Sales_SalesOrderHeaderSalesReasonController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Sales_SalesOrderHeaderSalesReasonController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Sales_SalesOrderHeaderSalesReason")]
        public async Task<ActionResult<IEnumerable<Sales.SalesOrderHeaderSalesReason>>> ListSalesOrderHeaderSalesReason(int pageIndex, int pageSize)
        {
            return await _db.Sales_SalesOrderHeaderSalesReason.OrderBy(x => x.SalesOrderID).ThenBy(x => x.SalesReasonID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("salesOrderID/{salesOrderID}/salesReasonID/{salesReasonID}", Name = "GetById_Sales_SalesOrderHeaderSalesReason")]
        public async Task<ActionResult<Sales.SalesOrderHeaderSalesReason>> GetSalesOrderHeaderSalesReason(int salesOrderID, int salesReasonID)
        {
            var result = await _db.Sales_SalesOrderHeaderSalesReason.FirstOrDefaultAsync(x => x.SalesOrderID == salesOrderID && x.SalesReasonID == salesReasonID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Sales_SalesOrderHeaderSalesReason")]
        public async Task<IActionResult> CreateSalesOrderHeaderSalesReason([FromBody] Sales.SalesOrderHeaderSalesReason value)
        {
            _db.Sales_SalesOrderHeaderSalesReason.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("salesOrderID/{salesOrderID}/salesReasonID/{salesReasonID}", Name = "Edit_Sales_SalesOrderHeaderSalesReason")]
        public async Task<IActionResult> EditSalesOrderHeaderSalesReason(int salesOrderID, int salesReasonID, [FromBody] Sales.SalesOrderHeaderSalesReason value)
        {
            var existing = await _db.Sales_SalesOrderHeaderSalesReason.FirstOrDefaultAsync(x => x.SalesOrderID == salesOrderID && x.SalesReasonID == salesReasonID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.SalesOrderID = value.SalesOrderID;
			existing.SalesReasonID = value.SalesReasonID;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Sales_SalesOrderHeaderSalesReason.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Sales_SalesOrderHeaderSalesReason")]
        public async Task<IActionResult> DeleteSalesOrderHeaderSalesReason(int salesOrderID, int salesReasonID)
        {
            var existing = await _db.Sales_SalesOrderHeaderSalesReason.FirstOrDefaultAsync(x => x.SalesOrderID == salesOrderID && x.SalesReasonID == salesReasonID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Sales_SalesOrderHeaderSalesReason.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}