// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Sales/ShoppingCartItem")]
    [ApiController]
    public class Sales_ShoppingCartItemController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Sales_ShoppingCartItemController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Sales_ShoppingCartItem")]
        public async Task<ActionResult<IEnumerable<Sales.ShoppingCartItem>>> ListShoppingCartItem(int pageIndex, int pageSize)
        {
            return await _db.Sales_ShoppingCartItem.OrderBy(x => x.ShoppingCartItemID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("{shoppingCartItemID}", Name = "GetById_Sales_ShoppingCartItem")]
        public async Task<ActionResult<Sales.ShoppingCartItem>> GetShoppingCartItem(int shoppingCartItemID)
        {
            var result = await _db.Sales_ShoppingCartItem.FirstOrDefaultAsync(x => x.ShoppingCartItemID == shoppingCartItemID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Sales_ShoppingCartItem")]
        public async Task<IActionResult> CreateShoppingCartItem([FromBody] Sales.ShoppingCartItem value)
        {
            _db.Sales_ShoppingCartItem.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("{shoppingCartItemID}", Name = "Edit_Sales_ShoppingCartItem")]
        public async Task<IActionResult> EditShoppingCartItem(int shoppingCartItemID, [FromBody] Sales.ShoppingCartItem value)
        {
            var existing = await _db.Sales_ShoppingCartItem.FirstOrDefaultAsync(x => x.ShoppingCartItemID == shoppingCartItemID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.ShoppingCartItemID = value.ShoppingCartItemID;
			existing.ShoppingCartID = value.ShoppingCartID;
			existing.Quantity = value.Quantity;
			existing.ProductID = value.ProductID;
			existing.DateCreated = value.DateCreated;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Sales_ShoppingCartItem.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Sales_ShoppingCartItem")]
        public async Task<IActionResult> DeleteShoppingCartItem(int shoppingCartItemID)
        {
            var existing = await _db.Sales_ShoppingCartItem.FirstOrDefaultAsync(x => x.ShoppingCartItemID == shoppingCartItemID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Sales_ShoppingCartItem.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}