// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Sales/Store")]
    [ApiController]
    public class Sales_StoreController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Sales_StoreController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Sales_Store")]
        public async Task<ActionResult<IEnumerable<Sales.Store>>> ListStore(int pageIndex, int pageSize)
        {
            return await _db.Sales_Store.OrderBy(x => x.BusinessEntityID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("{businessEntityID}", Name = "GetById_Sales_Store")]
        public async Task<ActionResult<Sales.Store>> GetStore(int businessEntityID)
        {
            var result = await _db.Sales_Store.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Sales_Store")]
        public async Task<IActionResult> CreateStore([FromBody] Sales.Store value)
        {
            _db.Sales_Store.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("{businessEntityID}", Name = "Edit_Sales_Store")]
        public async Task<IActionResult> EditStore(int businessEntityID, [FromBody] Sales.Store value)
        {
            var existing = await _db.Sales_Store.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.BusinessEntityID = value.BusinessEntityID;
			existing.Name = value.Name;
			existing.SalesPersonID = value.SalesPersonID;
			existing.Demographics = value.Demographics;
			existing.rowguid = value.rowguid;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Sales_Store.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Sales_Store")]
        public async Task<IActionResult> DeleteStore(int businessEntityID)
        {
            var existing = await _db.Sales_Store.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Sales_Store.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}