CREATE TABLE [Demo].WithAllNullDataTypes
(
	Id uniqueidentifier,
	ThisIsBigInt bigint NULL,
	ThisIsBinary binary NULL,
	ThisIsBit bit NULL,
	ThisIsChar char NULL,
	ThisIsDate date NULL,
	ThisIsDateTime datetime NULL,
	ThisIsDateTime2 datetime2 NULL,
	ThisIsDateTimeOffset datetimeoffset NULL,
	ThisIsDecimal decimal NULL,
	ThisIsFloat float NULL,
	ThisIsImage image NULL,
	ThisIsInt int NULL,
	ThisIsMoney money NULL,
	ThisIsNChar nchar NULL,
	ThisIsNText ntext NULL,
	ThisIsNumeric numeric NULL,
	ThisIsNvarchar nvarchar NULL,
	ThisIsReal real NULL,
	ThisIsSmallDateTime smalldatetime NULL,
	ThisIsSmallInt smallint NULL,
	ThisIsSmallMoney smallmoney NULL,
	ThisIsText text NULL,
	ThisIsTime time NULL,
	ThisIsTimestamp timestamp NULL,
	ThisIsTinyInt tinyint NULL,
	ThisIsUniqueIdentifier uniqueidentifier NULL,
	ThisIsVarBinary varbinary NULL,
	ThisIsVarchar varchar NULL,
	ThisIsXml xml NULL,
	ThisIsHierarchyId hierarchyid NULL,
	ThisIsGeography geography NULL,
	CONSTRAINT PK_WithAllNullDataTypes_Id PRIMARY KEY CLUSTERED(Id),
)