// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Person/Address")]
    [ApiController]
    public class Person_AddressController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Person_AddressController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Person_Address")]
        public async Task<ActionResult<IEnumerable<Person.Address>>> ListAddress(int pageIndex, int pageSize)
        {
            return await _db.Person_Address.OrderBy(x => x.AddressID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("{addressID}", Name = "GetById_Person_Address")]
        public async Task<ActionResult<Person.Address>> GetAddress(int addressID)
        {
            var result = await _db.Person_Address.FirstOrDefaultAsync(x => x.AddressID == addressID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Person_Address")]
        public async Task<IActionResult> CreateAddress([FromBody] Person.Address value)
        {
            _db.Person_Address.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("{addressID}", Name = "Edit_Person_Address")]
        public async Task<IActionResult> EditAddress(int addressID, [FromBody] Person.Address value)
        {
            var existing = await _db.Person_Address.FirstOrDefaultAsync(x => x.AddressID == addressID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.AddressID = value.AddressID;
			existing.AddressLine1 = value.AddressLine1;
			existing.AddressLine2 = value.AddressLine2;
			existing.City = value.City;
			existing.StateProvinceID = value.StateProvinceID;
			existing.PostalCode = value.PostalCode;
			existing.SpatialLocation = value.SpatialLocation;
			existing.rowguid = value.rowguid;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Person_Address.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Person_Address")]
        public async Task<IActionResult> DeleteAddress(int addressID)
        {
            var existing = await _db.Person_Address.FirstOrDefaultAsync(x => x.AddressID == addressID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Person_Address.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}