// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Person/AddressType")]
    [ApiController]
    public class Person_AddressTypeController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Person_AddressTypeController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Person_AddressType")]
        public async Task<ActionResult<IEnumerable<Person.AddressType>>> ListAddressType(int pageIndex, int pageSize)
        {
            return await _db.Person_AddressType.OrderBy(x => x.AddressTypeID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("{addressTypeID}", Name = "GetById_Person_AddressType")]
        public async Task<ActionResult<Person.AddressType>> GetAddressType(int addressTypeID)
        {
            var result = await _db.Person_AddressType.FirstOrDefaultAsync(x => x.AddressTypeID == addressTypeID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Person_AddressType")]
        public async Task<IActionResult> CreateAddressType([FromBody] Person.AddressType value)
        {
            _db.Person_AddressType.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("{addressTypeID}", Name = "Edit_Person_AddressType")]
        public async Task<IActionResult> EditAddressType(int addressTypeID, [FromBody] Person.AddressType value)
        {
            var existing = await _db.Person_AddressType.FirstOrDefaultAsync(x => x.AddressTypeID == addressTypeID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.AddressTypeID = value.AddressTypeID;
			existing.Name = value.Name;
			existing.rowguid = value.rowguid;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Person_AddressType.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Person_AddressType")]
        public async Task<IActionResult> DeleteAddressType(int addressTypeID)
        {
            var existing = await _db.Person_AddressType.FirstOrDefaultAsync(x => x.AddressTypeID == addressTypeID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Person_AddressType.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}