// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Person/BusinessEntityContact")]
    [ApiController]
    public class Person_BusinessEntityContactController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Person_BusinessEntityContactController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Person_BusinessEntityContact")]
        public async Task<ActionResult<IEnumerable<Person.BusinessEntityContact>>> ListBusinessEntityContact(int pageIndex, int pageSize)
        {
            return await _db.Person_BusinessEntityContact.OrderBy(x => x.BusinessEntityID).ThenBy(x => x.ContactTypeID).ThenBy(x => x.PersonID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("businessEntityID/{businessEntityID}/contactTypeID/{contactTypeID}/personID/{personID}", Name = "GetById_Person_BusinessEntityContact")]
        public async Task<ActionResult<Person.BusinessEntityContact>> GetBusinessEntityContact(int businessEntityID, int contactTypeID, int personID)
        {
            var result = await _db.Person_BusinessEntityContact.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID && x.ContactTypeID == contactTypeID && x.PersonID == personID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Person_BusinessEntityContact")]
        public async Task<IActionResult> CreateBusinessEntityContact([FromBody] Person.BusinessEntityContact value)
        {
            _db.Person_BusinessEntityContact.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("businessEntityID/{businessEntityID}/contactTypeID/{contactTypeID}/personID/{personID}", Name = "Edit_Person_BusinessEntityContact")]
        public async Task<IActionResult> EditBusinessEntityContact(int businessEntityID, int contactTypeID, int personID, [FromBody] Person.BusinessEntityContact value)
        {
            var existing = await _db.Person_BusinessEntityContact.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID && x.ContactTypeID == contactTypeID && x.PersonID == personID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.BusinessEntityID = value.BusinessEntityID;
			existing.PersonID = value.PersonID;
			existing.ContactTypeID = value.ContactTypeID;
			existing.rowguid = value.rowguid;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Person_BusinessEntityContact.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Person_BusinessEntityContact")]
        public async Task<IActionResult> DeleteBusinessEntityContact(int businessEntityID, int contactTypeID, int personID)
        {
            var existing = await _db.Person_BusinessEntityContact.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID && x.ContactTypeID == contactTypeID && x.PersonID == personID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Person_BusinessEntityContact.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}