// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Person/BusinessEntity")]
    [ApiController]
    public class Person_BusinessEntityController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Person_BusinessEntityController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Person_BusinessEntity")]
        public async Task<ActionResult<IEnumerable<Person.BusinessEntity>>> ListBusinessEntity(int pageIndex, int pageSize)
        {
            return await _db.Person_BusinessEntity.OrderBy(x => x.BusinessEntityID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("{businessEntityID}", Name = "GetById_Person_BusinessEntity")]
        public async Task<ActionResult<Person.BusinessEntity>> GetBusinessEntity(int businessEntityID)
        {
            var result = await _db.Person_BusinessEntity.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Person_BusinessEntity")]
        public async Task<IActionResult> CreateBusinessEntity([FromBody] Person.BusinessEntity value)
        {
            _db.Person_BusinessEntity.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("{businessEntityID}", Name = "Edit_Person_BusinessEntity")]
        public async Task<IActionResult> EditBusinessEntity(int businessEntityID, [FromBody] Person.BusinessEntity value)
        {
            var existing = await _db.Person_BusinessEntity.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.BusinessEntityID = value.BusinessEntityID;
			existing.rowguid = value.rowguid;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Person_BusinessEntity.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Person_BusinessEntity")]
        public async Task<IActionResult> DeleteBusinessEntity(int businessEntityID)
        {
            var existing = await _db.Person_BusinessEntity.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Person_BusinessEntity.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}