// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Person/EmailAddress")]
    [ApiController]
    public class Person_EmailAddressController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Person_EmailAddressController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Person_EmailAddress")]
        public async Task<ActionResult<IEnumerable<Person.EmailAddress>>> ListEmailAddress(int pageIndex, int pageSize)
        {
            return await _db.Person_EmailAddress.OrderBy(x => x.BusinessEntityID).ThenBy(x => x.EmailAddressID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("businessEntityID/{businessEntityID}/emailAddressID/{emailAddressID}", Name = "GetById_Person_EmailAddress")]
        public async Task<ActionResult<Person.EmailAddress>> GetEmailAddress(int businessEntityID, int emailAddressID)
        {
            var result = await _db.Person_EmailAddress.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID && x.EmailAddressID == emailAddressID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Person_EmailAddress")]
        public async Task<IActionResult> CreateEmailAddress([FromBody] Person.EmailAddress value)
        {
            _db.Person_EmailAddress.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("businessEntityID/{businessEntityID}/emailAddressID/{emailAddressID}", Name = "Edit_Person_EmailAddress")]
        public async Task<IActionResult> EditEmailAddress(int businessEntityID, int emailAddressID, [FromBody] Person.EmailAddress value)
        {
            var existing = await _db.Person_EmailAddress.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID && x.EmailAddressID == emailAddressID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.BusinessEntityID = value.BusinessEntityID;
			existing.EmailAddressID = value.EmailAddressID;
			existing.EmailAddress1 = value.EmailAddress1;
			existing.rowguid = value.rowguid;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Person_EmailAddress.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Person_EmailAddress")]
        public async Task<IActionResult> DeleteEmailAddress(int businessEntityID, int emailAddressID)
        {
            var existing = await _db.Person_EmailAddress.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID && x.EmailAddressID == emailAddressID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Person_EmailAddress.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}