// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Person/PersonPhone")]
    [ApiController]
    public class Person_PersonPhoneController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Person_PersonPhoneController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Person_PersonPhone")]
        public async Task<ActionResult<IEnumerable<Person.PersonPhone>>> ListPersonPhone(int pageIndex, int pageSize)
        {
            return await _db.Person_PersonPhone.OrderBy(x => x.BusinessEntityID).ThenBy(x => x.PhoneNumber).ThenBy(x => x.PhoneNumberTypeID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("businessEntityID/{businessEntityID}/phoneNumber/{phoneNumber}/phoneNumberTypeID/{phoneNumberTypeID}", Name = "GetById_Person_PersonPhone")]
        public async Task<ActionResult<Person.PersonPhone>> GetPersonPhone(int businessEntityID, string phoneNumber, int phoneNumberTypeID)
        {
            var result = await _db.Person_PersonPhone.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID && x.PhoneNumber == phoneNumber && x.PhoneNumberTypeID == phoneNumberTypeID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Person_PersonPhone")]
        public async Task<IActionResult> CreatePersonPhone([FromBody] Person.PersonPhone value)
        {
            _db.Person_PersonPhone.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("businessEntityID/{businessEntityID}/phoneNumber/{phoneNumber}/phoneNumberTypeID/{phoneNumberTypeID}", Name = "Edit_Person_PersonPhone")]
        public async Task<IActionResult> EditPersonPhone(int businessEntityID, string phoneNumber, int phoneNumberTypeID, [FromBody] Person.PersonPhone value)
        {
            var existing = await _db.Person_PersonPhone.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID && x.PhoneNumber == phoneNumber && x.PhoneNumberTypeID == phoneNumberTypeID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.BusinessEntityID = value.BusinessEntityID;
			existing.PhoneNumber = value.PhoneNumber;
			existing.PhoneNumberTypeID = value.PhoneNumberTypeID;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Person_PersonPhone.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Person_PersonPhone")]
        public async Task<IActionResult> DeletePersonPhone(int businessEntityID, string phoneNumber, int phoneNumberTypeID)
        {
            var existing = await _db.Person_PersonPhone.FirstOrDefaultAsync(x => x.BusinessEntityID == businessEntityID && x.PhoneNumber == phoneNumber && x.PhoneNumberTypeID == phoneNumberTypeID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Person_PersonPhone.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}