// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Person/Person_json")]
    [ApiController]
    public class Person_Person_jsonController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Person_Person_jsonController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Person_Person_json")]
        public async Task<ActionResult<IEnumerable<Person.Person_json>>> ListPerson_json(int pageIndex, int pageSize)
        {
            return await _db.Person_Person_json.OrderBy(x => x.PersonID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("{personID}", Name = "GetById_Person_Person_json")]
        public async Task<ActionResult<Person.Person_json>> GetPerson_json(int personID)
        {
            var result = await _db.Person_Person_json.FirstOrDefaultAsync(x => x.PersonID == personID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Person_Person_json")]
        public async Task<IActionResult> CreatePerson_json([FromBody] Person.Person_json value)
        {
            _db.Person_Person_json.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("{personID}", Name = "Edit_Person_Person_json")]
        public async Task<IActionResult> EditPerson_json(int personID, [FromBody] Person.Person_json value)
        {
            var existing = await _db.Person_Person_json.FirstOrDefaultAsync(x => x.PersonID == personID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.PersonID = value.PersonID;
			existing.PersonType = value.PersonType;
			existing.NameStyle = value.NameStyle;
			existing.Title = value.Title;
			existing.FirstName = value.FirstName;
			existing.MiddleName = value.MiddleName;
			existing.LastName = value.LastName;
			existing.Suffix = value.Suffix;
			existing.EmailPromotion = value.EmailPromotion;
			existing.AdditionalContactInfo = value.AdditionalContactInfo;
			existing.Demographics = value.Demographics;
			existing.rowguid = value.rowguid;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Person_Person_json.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Person_Person_json")]
        public async Task<IActionResult> DeletePerson_json(int personID)
        {
            var existing = await _db.Person_Person_json.FirstOrDefaultAsync(x => x.PersonID == personID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Person_Person_json.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}