// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Person/PhoneNumberType")]
    [ApiController]
    public class Person_PhoneNumberTypeController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Person_PhoneNumberTypeController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Person_PhoneNumberType")]
        public async Task<ActionResult<IEnumerable<Person.PhoneNumberType>>> ListPhoneNumberType(int pageIndex, int pageSize)
        {
            return await _db.Person_PhoneNumberType.OrderBy(x => x.PhoneNumberTypeID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("{phoneNumberTypeID}", Name = "GetById_Person_PhoneNumberType")]
        public async Task<ActionResult<Person.PhoneNumberType>> GetPhoneNumberType(int phoneNumberTypeID)
        {
            var result = await _db.Person_PhoneNumberType.FirstOrDefaultAsync(x => x.PhoneNumberTypeID == phoneNumberTypeID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Person_PhoneNumberType")]
        public async Task<IActionResult> CreatePhoneNumberType([FromBody] Person.PhoneNumberType value)
        {
            _db.Person_PhoneNumberType.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("{phoneNumberTypeID}", Name = "Edit_Person_PhoneNumberType")]
        public async Task<IActionResult> EditPhoneNumberType(int phoneNumberTypeID, [FromBody] Person.PhoneNumberType value)
        {
            var existing = await _db.Person_PhoneNumberType.FirstOrDefaultAsync(x => x.PhoneNumberTypeID == phoneNumberTypeID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.PhoneNumberTypeID = value.PhoneNumberTypeID;
			existing.Name = value.Name;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Person_PhoneNumberType.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Person_PhoneNumberType")]
        public async Task<IActionResult> DeletePhoneNumberType(int phoneNumberTypeID)
        {
            var existing = await _db.Person_PhoneNumberType.FirstOrDefaultAsync(x => x.PhoneNumberTypeID == phoneNumberTypeID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Person_PhoneNumberType.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}