// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Production/Culture")]
    [ApiController]
    public class Production_CultureController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Production_CultureController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Production_Culture")]
        public async Task<ActionResult<IEnumerable<Production.Culture>>> ListCulture(int pageIndex, int pageSize)
        {
            return await _db.Production_Culture.OrderBy(x => x.CultureID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("{cultureID}", Name = "GetById_Production_Culture")]
        public async Task<ActionResult<Production.Culture>> GetCulture(string cultureID)
        {
            var result = await _db.Production_Culture.FirstOrDefaultAsync(x => x.CultureID == cultureID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Production_Culture")]
        public async Task<IActionResult> CreateCulture([FromBody] Production.Culture value)
        {
            _db.Production_Culture.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("{cultureID}", Name = "Edit_Production_Culture")]
        public async Task<IActionResult> EditCulture(string cultureID, [FromBody] Production.Culture value)
        {
            var existing = await _db.Production_Culture.FirstOrDefaultAsync(x => x.CultureID == cultureID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.CultureID = value.CultureID;
			existing.Name = value.Name;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Production_Culture.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Production_Culture")]
        public async Task<IActionResult> DeleteCulture(string cultureID)
        {
            var existing = await _db.Production_Culture.FirstOrDefaultAsync(x => x.CultureID == cultureID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Production_Culture.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}