// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Production/Illustration")]
    [ApiController]
    public class Production_IllustrationController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Production_IllustrationController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Production_Illustration")]
        public async Task<ActionResult<IEnumerable<Production.Illustration>>> ListIllustration(int pageIndex, int pageSize)
        {
            return await _db.Production_Illustration.OrderBy(x => x.IllustrationID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("{illustrationID}", Name = "GetById_Production_Illustration")]
        public async Task<ActionResult<Production.Illustration>> GetIllustration(int illustrationID)
        {
            var result = await _db.Production_Illustration.FirstOrDefaultAsync(x => x.IllustrationID == illustrationID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Production_Illustration")]
        public async Task<IActionResult> CreateIllustration([FromBody] Production.Illustration value)
        {
            _db.Production_Illustration.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("{illustrationID}", Name = "Edit_Production_Illustration")]
        public async Task<IActionResult> EditIllustration(int illustrationID, [FromBody] Production.Illustration value)
        {
            var existing = await _db.Production_Illustration.FirstOrDefaultAsync(x => x.IllustrationID == illustrationID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.IllustrationID = value.IllustrationID;
			existing.Diagram = value.Diagram;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Production_Illustration.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Production_Illustration")]
        public async Task<IActionResult> DeleteIllustration(int illustrationID)
        {
            var existing = await _db.Production_Illustration.FirstOrDefaultAsync(x => x.IllustrationID == illustrationID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Production_Illustration.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}