// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Production/Location")]
    [ApiController]
    public class Production_LocationController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Production_LocationController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Production_Location")]
        public async Task<ActionResult<IEnumerable<Production.Location>>> ListLocation(int pageIndex, int pageSize)
        {
            return await _db.Production_Location.OrderBy(x => x.LocationID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("{locationID}", Name = "GetById_Production_Location")]
        public async Task<ActionResult<Production.Location>> GetLocation(short locationID)
        {
            var result = await _db.Production_Location.FirstOrDefaultAsync(x => x.LocationID == locationID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Production_Location")]
        public async Task<IActionResult> CreateLocation([FromBody] Production.Location value)
        {
            _db.Production_Location.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("{locationID}", Name = "Edit_Production_Location")]
        public async Task<IActionResult> EditLocation(short locationID, [FromBody] Production.Location value)
        {
            var existing = await _db.Production_Location.FirstOrDefaultAsync(x => x.LocationID == locationID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.LocationID = value.LocationID;
			existing.Name = value.Name;
			existing.CostRate = value.CostRate;
			existing.Availability = value.Availability;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Production_Location.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Production_Location")]
        public async Task<IActionResult> DeleteLocation(short locationID)
        {
            var existing = await _db.Production_Location.FirstOrDefaultAsync(x => x.LocationID == locationID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Production_Location.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}