// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Production/ProductInventory")]
    [ApiController]
    public class Production_ProductInventoryController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Production_ProductInventoryController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Production_ProductInventory")]
        public async Task<ActionResult<IEnumerable<Production.ProductInventory>>> ListProductInventory(int pageIndex, int pageSize)
        {
            return await _db.Production_ProductInventory.OrderBy(x => x.LocationID).ThenBy(x => x.ProductID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("locationID/{locationID}/productID/{productID}", Name = "GetById_Production_ProductInventory")]
        public async Task<ActionResult<Production.ProductInventory>> GetProductInventory(short locationID, int productID)
        {
            var result = await _db.Production_ProductInventory.FirstOrDefaultAsync(x => x.LocationID == locationID && x.ProductID == productID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Production_ProductInventory")]
        public async Task<IActionResult> CreateProductInventory([FromBody] Production.ProductInventory value)
        {
            _db.Production_ProductInventory.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("locationID/{locationID}/productID/{productID}", Name = "Edit_Production_ProductInventory")]
        public async Task<IActionResult> EditProductInventory(short locationID, int productID, [FromBody] Production.ProductInventory value)
        {
            var existing = await _db.Production_ProductInventory.FirstOrDefaultAsync(x => x.LocationID == locationID && x.ProductID == productID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.ProductID = value.ProductID;
			existing.LocationID = value.LocationID;
			existing.Shelf = value.Shelf;
			existing.Bin = value.Bin;
			existing.Quantity = value.Quantity;
			existing.rowguid = value.rowguid;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Production_ProductInventory.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Production_ProductInventory")]
        public async Task<IActionResult> DeleteProductInventory(short locationID, int productID)
        {
            var existing = await _db.Production_ProductInventory.FirstOrDefaultAsync(x => x.LocationID == locationID && x.ProductID == productID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Production_ProductInventory.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}