// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Production/ProductSubcategory")]
    [ApiController]
    public class Production_ProductSubcategoryController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Production_ProductSubcategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Production_ProductSubcategory")]
        public async Task<ActionResult<IEnumerable<Production.ProductSubcategory>>> ListProductSubcategory(int pageIndex, int pageSize)
        {
            return await _db.Production_ProductSubcategory.OrderBy(x => x.ProductSubcategoryID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("{productSubcategoryID}", Name = "GetById_Production_ProductSubcategory")]
        public async Task<ActionResult<Production.ProductSubcategory>> GetProductSubcategory(int productSubcategoryID)
        {
            var result = await _db.Production_ProductSubcategory.FirstOrDefaultAsync(x => x.ProductSubcategoryID == productSubcategoryID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Production_ProductSubcategory")]
        public async Task<IActionResult> CreateProductSubcategory([FromBody] Production.ProductSubcategory value)
        {
            _db.Production_ProductSubcategory.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("{productSubcategoryID}", Name = "Edit_Production_ProductSubcategory")]
        public async Task<IActionResult> EditProductSubcategory(int productSubcategoryID, [FromBody] Production.ProductSubcategory value)
        {
            var existing = await _db.Production_ProductSubcategory.FirstOrDefaultAsync(x => x.ProductSubcategoryID == productSubcategoryID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.ProductSubcategoryID = value.ProductSubcategoryID;
			existing.ProductCategoryID = value.ProductCategoryID;
			existing.Name = value.Name;
			existing.rowguid = value.rowguid;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Production_ProductSubcategory.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Production_ProductSubcategory")]
        public async Task<IActionResult> DeleteProductSubcategory(int productSubcategoryID)
        {
            var existing = await _db.Production_ProductSubcategory.FirstOrDefaultAsync(x => x.ProductSubcategoryID == productSubcategoryID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Production_ProductSubcategory.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}