// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Production/ProductDocument")]
    [ApiController]
    public class Production_ProductDocumentController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Production_ProductDocumentController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Production_ProductDocument")]
        public async Task<ActionResult<IEnumerable<Production.ProductDocument>>> ListProductDocument(int pageIndex, int pageSize)
        {
            return await _db.Production_ProductDocument.OrderBy(x => x.DocumentNode).ThenBy(x => x.ProductID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("documentNode/{documentNode}/productID/{productID}", Name = "GetById_Production_ProductDocument")]
        public async Task<ActionResult<Production.ProductDocument>> GetProductDocument(string documentNode, int productID)
        {
            var result = await _db.Production_ProductDocument.FirstOrDefaultAsync(x => x.DocumentNode == documentNode && x.ProductID == productID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Production_ProductDocument")]
        public async Task<IActionResult> CreateProductDocument([FromBody] Production.ProductDocument value)
        {
            _db.Production_ProductDocument.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("documentNode/{documentNode}/productID/{productID}", Name = "Edit_Production_ProductDocument")]
        public async Task<IActionResult> EditProductDocument(string documentNode, int productID, [FromBody] Production.ProductDocument value)
        {
            var existing = await _db.Production_ProductDocument.FirstOrDefaultAsync(x => x.DocumentNode == documentNode && x.ProductID == productID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.ProductID = value.ProductID;
			existing.DocumentNode = value.DocumentNode;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Production_ProductDocument.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Production_ProductDocument")]
        public async Task<IActionResult> DeleteProductDocument(string documentNode, int productID)
        {
            var existing = await _db.Production_ProductDocument.FirstOrDefaultAsync(x => x.DocumentNode == documentNode && x.ProductID == productID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Production_ProductDocument.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}