// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Production/ProductModelIllustration")]
    [ApiController]
    public class Production_ProductModelIllustrationController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Production_ProductModelIllustrationController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Production_ProductModelIllustration")]
        public async Task<ActionResult<IEnumerable<Production.ProductModelIllustration>>> ListProductModelIllustration(int pageIndex, int pageSize)
        {
            return await _db.Production_ProductModelIllustration.OrderBy(x => x.IllustrationID).ThenBy(x => x.ProductModelID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("illustrationID/{illustrationID}/productModelID/{productModelID}", Name = "GetById_Production_ProductModelIllustration")]
        public async Task<ActionResult<Production.ProductModelIllustration>> GetProductModelIllustration(int illustrationID, int productModelID)
        {
            var result = await _db.Production_ProductModelIllustration.FirstOrDefaultAsync(x => x.IllustrationID == illustrationID && x.ProductModelID == productModelID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Production_ProductModelIllustration")]
        public async Task<IActionResult> CreateProductModelIllustration([FromBody] Production.ProductModelIllustration value)
        {
            _db.Production_ProductModelIllustration.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("illustrationID/{illustrationID}/productModelID/{productModelID}", Name = "Edit_Production_ProductModelIllustration")]
        public async Task<IActionResult> EditProductModelIllustration(int illustrationID, int productModelID, [FromBody] Production.ProductModelIllustration value)
        {
            var existing = await _db.Production_ProductModelIllustration.FirstOrDefaultAsync(x => x.IllustrationID == illustrationID && x.ProductModelID == productModelID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.ProductModelID = value.ProductModelID;
			existing.IllustrationID = value.IllustrationID;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Production_ProductModelIllustration.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Production_ProductModelIllustration")]
        public async Task<IActionResult> DeleteProductModelIllustration(int illustrationID, int productModelID)
        {
            var existing = await _db.Production_ProductModelIllustration.FirstOrDefaultAsync(x => x.IllustrationID == illustrationID && x.ProductModelID == productModelID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Production_ProductModelIllustration.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}