// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Production/ProductModel")]
    [ApiController]
    public class Production_ProductModelController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Production_ProductModelController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Production_ProductModel")]
        public async Task<ActionResult<IEnumerable<Production.ProductModel>>> ListProductModel(int pageIndex, int pageSize)
        {
            return await _db.Production_ProductModel.OrderBy(x => x.ProductModelID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("{productModelID}", Name = "GetById_Production_ProductModel")]
        public async Task<ActionResult<Production.ProductModel>> GetProductModel(int productModelID)
        {
            var result = await _db.Production_ProductModel.FirstOrDefaultAsync(x => x.ProductModelID == productModelID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Production_ProductModel")]
        public async Task<IActionResult> CreateProductModel([FromBody] Production.ProductModel value)
        {
            _db.Production_ProductModel.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("{productModelID}", Name = "Edit_Production_ProductModel")]
        public async Task<IActionResult> EditProductModel(int productModelID, [FromBody] Production.ProductModel value)
        {
            var existing = await _db.Production_ProductModel.FirstOrDefaultAsync(x => x.ProductModelID == productModelID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.ProductModelID = value.ProductModelID;
			existing.Name = value.Name;
			existing.CatalogDescription = value.CatalogDescription;
			existing.Instructions = value.Instructions;
			existing.rowguid = value.rowguid;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Production_ProductModel.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Production_ProductModel")]
        public async Task<IActionResult> DeleteProductModel(int productModelID)
        {
            var existing = await _db.Production_ProductModel.FirstOrDefaultAsync(x => x.ProductModelID == productModelID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Production_ProductModel.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}