// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Production/ProductModelProductDescriptionCulture")]
    [ApiController]
    public class Production_ProductModelProductDescriptionCultureController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Production_ProductModelProductDescriptionCultureController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Production_ProductModelProductDescriptionCulture")]
        public async Task<ActionResult<IEnumerable<Production.ProductModelProductDescriptionCulture>>> ListProductModelProductDescriptionCulture(int pageIndex, int pageSize)
        {
            return await _db.Production_ProductModelProductDescriptionCulture.OrderBy(x => x.CultureID).ThenBy(x => x.ProductDescriptionID).ThenBy(x => x.ProductModelID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("cultureID/{cultureID}/productDescriptionID/{productDescriptionID}/productModelID/{productModelID}", Name = "GetById_Production_ProductModelProductDescriptionCulture")]
        public async Task<ActionResult<Production.ProductModelProductDescriptionCulture>> GetProductModelProductDescriptionCulture(string cultureID, int productDescriptionID, int productModelID)
        {
            var result = await _db.Production_ProductModelProductDescriptionCulture.FirstOrDefaultAsync(x => x.CultureID == cultureID && x.ProductDescriptionID == productDescriptionID && x.ProductModelID == productModelID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Production_ProductModelProductDescriptionCulture")]
        public async Task<IActionResult> CreateProductModelProductDescriptionCulture([FromBody] Production.ProductModelProductDescriptionCulture value)
        {
            _db.Production_ProductModelProductDescriptionCulture.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("cultureID/{cultureID}/productDescriptionID/{productDescriptionID}/productModelID/{productModelID}", Name = "Edit_Production_ProductModelProductDescriptionCulture")]
        public async Task<IActionResult> EditProductModelProductDescriptionCulture(string cultureID, int productDescriptionID, int productModelID, [FromBody] Production.ProductModelProductDescriptionCulture value)
        {
            var existing = await _db.Production_ProductModelProductDescriptionCulture.FirstOrDefaultAsync(x => x.CultureID == cultureID && x.ProductDescriptionID == productDescriptionID && x.ProductModelID == productModelID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.ProductModelID = value.ProductModelID;
			existing.ProductDescriptionID = value.ProductDescriptionID;
			existing.CultureID = value.CultureID;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Production_ProductModelProductDescriptionCulture.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Production_ProductModelProductDescriptionCulture")]
        public async Task<IActionResult> DeleteProductModelProductDescriptionCulture(string cultureID, int productDescriptionID, int productModelID)
        {
            var existing = await _db.Production_ProductModelProductDescriptionCulture.FirstOrDefaultAsync(x => x.CultureID == cultureID && x.ProductDescriptionID == productDescriptionID && x.ProductModelID == productModelID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Production_ProductModelProductDescriptionCulture.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}