// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Production/ScrapReason")]
    [ApiController]
    public class Production_ScrapReasonController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Production_ScrapReasonController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Production_ScrapReason")]
        public async Task<ActionResult<IEnumerable<Production.ScrapReason>>> ListScrapReason(int pageIndex, int pageSize)
        {
            return await _db.Production_ScrapReason.OrderBy(x => x.ScrapReasonID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("{scrapReasonID}", Name = "GetById_Production_ScrapReason")]
        public async Task<ActionResult<Production.ScrapReason>> GetScrapReason(short scrapReasonID)
        {
            var result = await _db.Production_ScrapReason.FirstOrDefaultAsync(x => x.ScrapReasonID == scrapReasonID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Production_ScrapReason")]
        public async Task<IActionResult> CreateScrapReason([FromBody] Production.ScrapReason value)
        {
            _db.Production_ScrapReason.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("{scrapReasonID}", Name = "Edit_Production_ScrapReason")]
        public async Task<IActionResult> EditScrapReason(short scrapReasonID, [FromBody] Production.ScrapReason value)
        {
            var existing = await _db.Production_ScrapReason.FirstOrDefaultAsync(x => x.ScrapReasonID == scrapReasonID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.ScrapReasonID = value.ScrapReasonID;
			existing.Name = value.Name;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Production_ScrapReason.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Production_ScrapReason")]
        public async Task<IActionResult> DeleteScrapReason(short scrapReasonID)
        {
            var existing = await _db.Production_ScrapReason.FirstOrDefaultAsync(x => x.ScrapReasonID == scrapReasonID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Production_ScrapReason.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}