// DISCLAIMER
// This file contains auto generated code.
// Changes to this file may be overwritten when the files are regenerated.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedApi.Controllers
{
    [Route("api/Production/WorkOrder")]
    [ApiController]
    public class Production_WorkOrderController : ControllerBase
    {
        private readonly ApplicationDbContext _db;

        public Production_WorkOrderController(ApplicationDbContext db)
        {
            _db = db;
        }

		[HttpGet]
        [Route("", Name = "List_Production_WorkOrder")]
        public async Task<ActionResult<IEnumerable<Production.WorkOrder>>> ListWorkOrder(int pageIndex, int pageSize)
        {
            return await _db.Production_WorkOrder.OrderBy(x => x.WorkOrderID).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
        }

		[HttpGet]
        [Route("{workOrderID}", Name = "GetById_Production_WorkOrder")]
        public async Task<ActionResult<Production.WorkOrder>> GetWorkOrder(int workOrderID)
        {
            var result = await _db.Production_WorkOrder.FirstOrDefaultAsync(x => x.WorkOrderID == workOrderID);
            if (result == null)
            {
                return NotFound();
            }
            return result;
        }

		[HttpPost]
        [Route("", Name = "Create_Production_WorkOrder")]
        public async Task<IActionResult> CreateWorkOrder([FromBody] Production.WorkOrder value)
        {
            _db.Production_WorkOrder.Add(value);
            await _db.SaveChangesAsync();
            return Ok(value);
        }

		[HttpPut("{workOrderID}", Name = "Edit_Production_WorkOrder")]
        public async Task<IActionResult> EditWorkOrder(int workOrderID, [FromBody] Production.WorkOrder value)
        {
            var existing = await _db.Production_WorkOrder.FirstOrDefaultAsync(x => x.WorkOrderID == workOrderID);
            if (existing == null)
            {
                return NotFound();
            }

			existing.WorkOrderID = value.WorkOrderID;
			existing.ProductID = value.ProductID;
			existing.OrderQty = value.OrderQty;
			existing.StockedQty = value.StockedQty;
			existing.ScrappedQty = value.ScrappedQty;
			existing.StartDate = value.StartDate;
			existing.EndDate = value.EndDate;
			existing.DueDate = value.DueDate;
			existing.ScrapReasonID = value.ScrapReasonID;
			existing.ModifiedDate = value.ModifiedDate;

            _db.Production_WorkOrder.Update(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		[HttpDelete("", Name = "Delete_Production_WorkOrder")]
        public async Task<IActionResult> DeleteWorkOrder(int workOrderID)
        {
            var existing = await _db.Production_WorkOrder.FirstOrDefaultAsync(x => x.WorkOrderID == workOrderID);
            if (existing == null)
            {
                return NotFound();
            }
            _db.Production_WorkOrder.Remove(existing);
            await _db.SaveChangesAsync();
            return NoContent();
        }

		// No GetByUniqueKeyActions generated

		// No EditByUniqueKeyActions generated

		// No DeleteByUniqueKeyActions generated

	}
}